from entity.WordJapanese import WordJapanese
from utility.japonais import transform_to_hiragana

WORD_HIRAGANA = [
    WordJapanese(transform_to_hiragana("ha", "i"), "Hai", "Oui"),
    WordJapanese(transform_to_hiragana("i", "i", "e"), "Īe", "Non"),
    WordJapanese(transform_to_hiragana("o", "ne", "ga", "i", "shi", "ma", "su"), "onegaishimasu", "S'il vous plaît"),
    WordJapanese(transform_to_hiragana("a", "ri", "ga", "to"), "arigato", "Merci"),
    WordJapanese(transform_to_hiragana("do", "allongement", "i", "ta", "shi", "ma", "shi", "te"), "Dōitashimashite", "il n'y a pas de quoi"),
    WordJapanese(transform_to_hiragana("o", "ha", "yo", "allongement"), "ohayō", "Bonjour (matin)"),
    WordJapanese(transform_to_hiragana("ko", "n", "ni", "chi", "ha"), "konichiwa", "Bonjour (journée)"),
    WordJapanese(transform_to_hiragana("ko", "n", "ba", "n", "ha"), "konbanwa", "Bonsoir"),
    WordJapanese(transform_to_hiragana("sa", "yo", "allongement", "na", "ra"), "sayōnara", "Au revoir"),
    WordJapanese(transform_to_hiragana("o", "ya", "su", "mi"), "oyasumi", "Bonne nuit"),
    WordJapanese(transform_to_hiragana("do", "allongement", "zo"), "dōzo", "Je vous en prie"),
    WordJapanese(transform_to_hiragana("i", "ta", "da", "ki", "ma", "su"), "itadakimasu", "Bon appétit"),
    WordJapanese(transform_to_hiragana("su", "mi", "ma", "se", "n"), "sumimasen", "Excusez-moi"),
    WordJapanese(transform_to_hiragana("go", "me", "n"), "gomen", "Pardonne(z)-moi"),
    WordJapanese(transform_to_hiragana("i", "pause", "te", "ki", "ma", "su"), "itekimasu", "J'y vais"),
    WordJapanese(transform_to_hiragana("ta", "da", "i", "ma"), "tadaima", "Je suis rentré"),
    WordJapanese(transform_to_hiragana("i", "ra", "pause", "shi", "ya", "i", "ma", "se"), "irashiyaimase", "Bienvenue"),
    WordJapanese(transform_to_hiragana("yo", "u", "ko", "so"), "yōkoso", "Bienvenue"),
    WordJapanese(transform_to_hiragana("a", "hi", "ru"), "ahiru", "Canard"),
    WordJapanese(transform_to_hiragana("i", "ru", "ka"), "iruka", "Dophin"),
    WordJapanese(transform_to_hiragana("i", "n", "ko"), "inko", "Perruche"),
    WordJapanese(transform_to_hiragana("ka", "e", "ru"), "kaeru", "Grenouille"),
    WordJapanese(transform_to_hiragana("ka", "mo", "me"), "kamome", "Mouette"),
    WordJapanese(transform_to_hiragana("ka", "ra", "su"), "karasu", "Corbeau"),
    WordJapanese(transform_to_hiragana("ki", "tsu", "ne"), "kitsune", "Renard"),
    WordJapanese(transform_to_hiragana("ki", "ri", "n"), "kirin", "Girafe"),
    WordJapanese(transform_to_hiragana("ku", "ji", "ra"), "kujira", "Baleine"),
    WordJapanese(transform_to_hiragana("ko", "a", "ra"), "koara", "Koala"),
    WordJapanese(transform_to_hiragana("go", "ri", "ra"), "gorira", "Gorille"),
    WordJapanese(transform_to_hiragana("sa", "so", "ri"), "sasori", "Scorpion"),
    WordJapanese(transform_to_hiragana("su", "zu", "me"), "suzume", "Moineau"),
    WordJapanese(transform_to_hiragana("ne", "zu", "mi"), "nezumi", "Souris"),
    WordJapanese(transform_to_hiragana("pa", "n", "da"), "panda", "Panda"),
    WordJapanese(transform_to_hiragana("hi", "tsu", "ji"), "hitsuji", "Mouton"),
    WordJapanese(transform_to_hiragana("mo", "gu", "ra"), "mogura", "Taupe"),
    WordJapanese(transform_to_hiragana("ne", "ko"), "neko", "Chat"),
    WordJapanese(transform_to_hiragana("i", "nu"), "inu", "Chien"),
    WordJapanese(transform_to_hiragana("ka", "me"), "kame", "Tortue"),
    WordJapanese(transform_to_hiragana("bu", "ta"), "buta", "Cochon"),
    WordJapanese(transform_to_hiragana("wa", "ni"), "wani", "Crocodile"),
    WordJapanese(transform_to_hiragana("ku", "ma"), "kuma", "Ours"),
    WordJapanese(transform_to_hiragana("sa", "ru"), "saru", "Singe"),
    WordJapanese(transform_to_hiragana("zo", "u"), "zou", "Elephant"),
    WordJapanese(transform_to_hiragana("he", "bi"), "hebi", "Serpent"),
    WordJapanese(transform_to_hiragana("to", "ra"), "tora", "Tigre"),
    WordJapanese(transform_to_hiragana("u", "shi"), "ushi", "Vache"),
    WordJapanese(transform_to_hiragana("ta", "ka"), "taka", "Faucon"),
    WordJapanese(transform_to_hiragana("ha", "to"), "hato", "Pigeon"),
    WordJapanese(transform_to_hiragana("u", "ma"), "uma", "Cheval"),
    WordJapanese(transform_to_hiragana("ri", "su"), "risu", "Ecureil"),
    WordJapanese(transform_to_hiragana("ya", "gi"), "yagi", "Chèvre"),
    WordJapanese(transform_to_hiragana("ka", "ba"), "kaba", "Hippopotame"),
    WordJapanese(transform_to_hiragana("ku", "mo"), "kumo", "Araignée"),
    WordJapanese(transform_to_hiragana("o", "o", "ka", "mi"), "Ōkami", "Loup")
]